<?php

/**
 * @file
 * Contains college_schedule.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Menu\MenuTreeParameters;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function college_schedule_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the college_schedule module.
    case 'help.page.college_schedule':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('College schedule') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function college_schedule_theme() {
  $theme = [];
  $theme['schedule_event'] = [
    'render element' => 'elements',
    'file' => 'schedule_event.page.inc',
    'template' => 'schedule_event',
  ];
  $theme['schedule_event_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'schedule_event.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function college_schedule_theme_suggestions_schedule_event(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#schedule_event'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'schedule_event__' . $sanitized_view_mode;
  $suggestions[] = 'schedule_event__' . $entity->bundle();
  $suggestions[] = 'schedule_event__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'schedule_event__' . $entity->id();
  $suggestions[] = 'schedule_event__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

function college_schedule_toolbar() {


  $menu_tree = \Drupal::service('toolbar.menu_tree');
  $parameters = new MenuTreeParameters();
  $parameters->setRoot('college_schedule.toolbar')->excludeRoot()->setMaxDepth(4)->onlyEnabledLinks();
  $tree = $menu_tree->load(NULL, $parameters);
  $manipulators = [
    ['callable' => 'menu.default_tree_manipulators:checkAccess'],
    ['callable' => 'menu.default_tree_manipulators:generateIndexAndSort'],
    ['callable' => 'toolbar_tools_menu_navigation_links'],
  ];
  $tree = $menu_tree->transform($tree, $manipulators);

  $items['dashboard'] = [
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'link',
      '#title' => t('Schedule'),
      '#url' => Url::fromRoute('college_schedule.toolbar'),
      '#options' => [
        'attributes' => [
          'class' => ['toolbar-item', 'trigger', 'toolbar-icon', 'toolbar-icon-schedule-dashboard'],
        ],
      ],
    ],
    'tray' => $menu_tree->build($tree),
    '#weight' => -2,
    '#attached' => [
     // 'library' => ['braslavskie_ltd/toolbar'],
    ],
  ];
  return $items;
}

/**
 * Implements hook_views_data_alter().
 */
function college_schedule_views_data_alter(array &$data) {
  //dpm($data);
}
