<?php

/**
 * @file
 * Contains college_schedule.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function college_schedule_ui_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the college_schedule module.
    case 'help.page.college_schedule':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('College schedule') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_theme().
 */
function college_schedule_ui_theme($existing, $type, $theme, $path) {
  $themes = [];
  $themes['schedule_day_element'] = [
    'variables' => [
      'content' => '',
      'items' => NULL,
      'hours' => NULL,
      'attributes' => [],
    ],
  ];
  return $themes;
}
